import sys
import os

# パスを通す
sys.path.append(os.getcwd())

from tools.data_fetcher import DataFetcher

def test_sentiment_input_flow():
    print("--- Test: Data Flow for Sentiment Analysis ---")
    
    # 擬似データ
    goal = "Analyze This"
    market_data = "Price is up"
    raw_sns_data = [{"title": "Test", "snippet": "Snippet", "url": "URL"}]
    context = "Market Context"
    constraints = "Strict constraints"
    
    # neo_main.py のロジックを再現
    formatted_sns = DataFetcher.format_for_crew(raw_sns_data)
    print(f"1. Formatted SNS Data:\n{formatted_sns}")
    
    # 引数の食い違いを再現
    # neo_main.py: inputs = DataFetcher.create_sentiment_input(goal, context, constraints)
    # create_sentiment_input(goal, market_data, sns_data)
    try:
        inputs = DataFetcher.create_sentiment_input(goal, context, constraints)
        print("\n2. Inputs generated by create_sentiment_input (as called in neo_main):")
        print(f"Goal: {inputs['goal']}")
        print(f"Context (what SentimentCrew receives): {inputs['context']}")
        # print(f"Constraints: {inputs['constraints']}")
    except Exception as e:
        print(f"\nError calling create_sentiment_input: {e}")

    # 正しい呼び出し方（想定）
    print("\n--- Correct Usage (Hypothesis) ---")
    inputs_correct = DataFetcher.create_sentiment_input(goal, market_data, formatted_sns)
    print(f"Context (Correct): {inputs_correct['context']}")

if __name__ == "__main__":
    test_sentiment_input_flow()
