import json
import logging
from typing import Dict, Any, List
from tools.paper_wallet import PaperWallet
# from tools.market_data import MarketData  <-- トップレベルでのインポートを廃止

logger = logging.getLogger(__name__)

class PaperTraderAgent:
    """
    Executes trading strategies generated by the Planning Crew in a simulated environment.
    Connects Strategy (Intent) -> Action (Paper Wallet).
    """

    def __init__(self, wallet_path: str = "data/paper_wallet.json"):
        self.wallet = PaperWallet(data_path=wallet_path)
        self.target_token = "VIRTUAL" # Default target for now (Proxy for Virtuals Ecosystem)

    def execute_strategy(self, strategy_json: Dict[str, Any]) -> Dict[str, Any]:
        """
        Parses the strategy directive and executes trades.
        """
        # ここで遅延インポートを行う (循環参照やロード順序の問題を回避)
        from tools.market_data import MarketData

        logger.info("🤖 PaperTrader: Analyzing Strategy Directive...")
        
        # 1. Extract Key Metrics
        virtuals_payload = strategy_json.get("virtuals_payload", {})
        risk_policy = virtuals_payload.get("risk_policy", {})
        action_directive = virtuals_payload.get("action_directive", "")
        
        # 2. Determine Action (Buy/Sell/Hold) based on Risk Policy & Directive
        
        # Get Current Market Price
        market_data = MarketData.get_token_price(self.target_token)
        current_price = market_data.get("priceUsd")
        
        if not current_price:
             return {"status": "error", "message": "Failed to fetch market price for execution."}
        
        current_price = float(current_price)
        
        # Logic: Determine Trade Action
        action = "HOLD"
        reason = "No clear signal"
        amount_usd = 0.0
        
        max_ltv = risk_policy.get("max_ltv", 0.5)
        
        # Check current portfolio balance
        usd_balance = self.wallet.get_balance()
        current_holdings_value = self.wallet.get_portfolio_value({self.target_token: current_price}) - usd_balance

        if max_ltv >= 0.65:
            action = "BUY"
            amount_usd = usd_balance * 0.1 # Buy with 10% of available cash
            reason = f"Risk On (LTV {max_ltv} >= 0.65). Increasing exposure."
        elif max_ltv <= 0.4:
            action = "SELL"
            # Sell 10% of current holdings value
            amount_usd = current_holdings_value * 0.1 
            reason = f"Risk Off (LTV {max_ltv} <= 0.4). Reducing exposure."
        else:
            action = "HOLD"
            reason = f"Neutral Risk Policy (LTV {max_ltv}). maintaining position."

        # 3. Execute Trade
        result = {}
        if action == "BUY" and amount_usd > 10.0: # Minimum trade size
            result = self.wallet.execute_trade(self.target_token, "BUY", amount_usd, current_price, reason)
        elif action == "SELL" and amount_usd > 10.0:
            result = self.wallet.execute_trade(self.target_token, "SELL", amount_usd, current_price, reason)
        else:
            result = {"status": "skipped", "reason": reason if amount_usd <= 10.0 else "Amount too small"}

        # 4. Generate Report
        portfolio_summary = {
            "total_value_usd": self.wallet.get_portfolio_value({self.target_token: current_price}),
            "usd_balance": self.wallet.get_balance(),
            "virtual_holdings": self.wallet.get_holding(self.target_token),
            "last_action": action,
            "execution_result": result
        }
        
        logger.info(f"✅ PaperTrader Execution Complete: {action} ({reason})")
        return portfolio_summary

if __name__ == "__main__":
    # Test Run
    agent = PaperTraderAgent()
    mock_strategy = {
        "virtuals_payload": {
            "risk_policy": {"max_ltv": 0.7},
            "action_directive": "Aggressive Growth"
        }
    }
    print(agent.execute_strategy(mock_strategy))
