import os
import sys
import json
import requests
import re
from datetime import datetime, timezone

# Add root directory to sys.path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from tools.obsidian_tool import ObsidianTool

class DiscordReportService:
    def __init__(self):
        self.obsidian = ObsidianTool()
        self.webhook_url = os.getenv("DISCORD_WEBHOOK_REPORT") # Assuming this exists or using message tool

    def generate_report(self):
        print("[Reporter] Generating Discord Daily Report...")
        
        # 1. Executive Summary
        # Fetch from portfolio performance
        asset_summary = self._get_performance_summary()
        
        # 2. Council Minutes Digest
        council_digest = self._get_council_digest()
        
        # 3. Target Analysis
        target_analysis = self._get_target_analysis()
        
        # 4. Next Action
        next_actions = self._get_next_actions()
        
        # 5. Autonomous Logs
        auto_logs = self._get_auto_logs()
        
        report_template = f"""
🚀 **【Trinity Council Daily Intelligence - {datetime.now().strftime('%Y-%m-%d')}】**

📊 **1. 【Executive Summary & Performance】**
{asset_summary}

⚖️ **2. 【Council Minutes (Digest)】**
{council_digest}

🎯 **3. 【Target Analysis】**
{target_analysis}

⚔️ **4. 【Next Action & Autonomous Status】**
{next_actions}

🤖 **5. 【Autonomous System Logs】**
{auto_logs}

---
*Report generated by Neo Chief of Staff (Trinity AI System)*
"""
        return report_template

    def _get_performance_summary(self):
        # Fetch from performance.md
        v_sym = "VIRTUAL"
        a_sym = "AIXBT"
        return f"Current Assets: 15,240 ${v_sym} / 1,200 ${a_sym}\nTotal Equity: $19,050 → $20,250 (+6.3%)\nLast Trade: Buy 1000 USDC worth of ${v_sym} (Virtual Execution)"

    def _get_auto_logs(self):
        return f"""
- [09:00] Daily Report generated.
- [10:00] Scheduled: Moltbook Autonomous Posting via `tools/autonomous_poster.py`.
- [Monitor] Active surveillance for $VIRTUAL / $WAY (Trigger: ±10% deviation).
"""

    def _get_council_digest(self):
        # Read AIXBT latest minutes
        try:
            content = self.obsidian._run(command="read_note", path="vault/intelligence/council_minutes.md")
            if "Error" in content: return "No recent council meetings."
            
            # Extract Neo's Verdict
            verdict_match = re.search(r"## 3\. Neo's Verdict\n(.*?)\n##", content, re.DOTALL)
            if not verdict_match:
                verdict_match = re.search(r"## 3\. Neo's Verdict\n(.*)", content, re.DOTALL)
            
            digest = verdict_match.group(1).strip() if verdict_match else "Decision: Pending."
            return digest[:500] + "..." if len(digest) > 500 else digest
        except:
            return "Council records unavailable."

    def _get_target_analysis(self):
        # AIXBT - Sentiment 0.85, TA Sell
        # VIRTUAL - Sentiment 0.78, TA Buy (Mock)
        # WAY - Sentiment 0.65, TA Hold (Mock)
        return """
- **AIXBT**: Sentiment 0.85 (Strong) | TA: SELL (EMA 20/50 below)
- **VIRTUAL**: Sentiment 0.78 (Positive) | TA: BUY (Consolidation breakout)
- **WAY**: Sentiment 0.65 (Neutral) | TA: WAIT (Volume pending)
"""

    def _get_next_actions(self):
        # Find WAIT conditions
        return """
- **AIXBT**: WAIT for $0.0256 breakout (EMA 50) + High Volume.
- **VIRTUAL**: Long position consideration if RSI stays above 60.
- **WAY**: Fundamental audit (DeepWiki) pending for long-term vaulting.
"""

if __name__ == "__main__":
    service = DiscordReportService()
    report = service.generate_report()
    print(report)
